-- STEP 1: テーブル構造を修正します
-- TagテーブルとQuestionTagテーブルのidカラムが自動採番でない場合に備えて、
-- IDENTITYプロパティを追加して自動採番されるように設定します。
-- もし既に設定済みの場合でもエラーにならないように、IF NOT EXISTS 構文のような安全な処理を試みますが、
-- PostgreSQLのALTER TABLEには直接的なIF NOT EXISTSがないため、エラーが出た場合はこの部分をスキップしてください。
-- ただし、エラーメッセージから見て、この処理は必要です。

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'Tag'
        AND column_name = 'id'
        AND identity_generation IS NOT NULL
    ) THEN
        ALTER TABLE public."Tag" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
        AND table_name = 'QuestionTag'
        AND column_name = 'id'
        AND identity_generation IS NOT NULL
    ) THEN
        ALTER TABLE public."QuestionTag" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;


-- STEP 2: 質問、カテゴリ、タグをまとめて更新する関数を作成します
-- (前回エラーになったシーケンスへの権限付与は不要なため削除しました)
CREATE OR REPLACE FUNCTION update_question_with_tags(
    p_question_id UUID,
    p_title TEXT,
    p_description TEXT,
    p_category_id UUID,
    p_tag_names TEXT[]
)
RETURNS VOID AS $$
DECLARE
    tag_name TEXT;
    v_tag_id BIGINT; -- idの型がBIGINTの可能性を考慮
BEGIN
    -- 1. Questionテーブルの基本情報を更新
    UPDATE public."Question"
    SET
        title = p_title,
        description = p_description,
        category_id = p_category_id
    WHERE id = p_question_id;

    -- 2. 既存のタグ関連を一旦削除
    DELETE FROM public."QuestionTag"
    WHERE question_id = p_question_id;

    -- 3. 新しいタグを処理
    IF array_length(p_tag_names, 1) > 0 THEN
        FOREACH tag_name IN ARRAY p_tag_names
        LOOP
            -- タグが存在するか確認し、なければ新規作成(UPSERT)
            INSERT INTO public."Tag" (name)
            VALUES (TRIM(tag_name))
            ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
            RETURNING id INTO v_tag_id;

            -- QuestionTagテーブルに新しい関連を挿入
            INSERT INTO public."QuestionTag" (question_id, tag_id)
            VALUES (p_question_id, v_tag_id);
        END LOOP;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- STEP 3: この関数を実行できる権限を付与します
GRANT EXECUTE ON FUNCTION public.update_question_with_tags(UUID, TEXT, TEXT, UUID, TEXT[]) TO authenticated;

-- STEP 4: 念のため、必要なテーブルへの権限を確認・付与します
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."Question" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."Tag" TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public."QuestionTag" TO authenticated;
