import type { Metadata } from "next";
import { GeistSans } from 'geist/font/sans'
import { GeistMono } from 'geist/font/mono'
import './globals.css'
// import Header from '@/components/Header' // デバッグのためコメントアウト
import { cn } from '@/lib/utils'
// import SubHeader from '@/components/SubHeader' // デバッグのためコメントアウト

const font = GeistSans
const monoFont = GeistMono

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ja">
      <body className={cn('antialiased bg-custom-blue-50 text-teal-950', font.variable, monoFont.variable)}>
        {/* <Header /> */}
        {/* <SubHeader /> */}
        <main>{children}</main>
      </body>
    </html>
  )
}
